rootdir := ''
prefix := '/usr'

base-dir := absolute_path(clean(rootdir / prefix))

desktop := APPID + '.desktop'
desktop-src := APPID + '.desktop'
desktop-dst := clean(rootdir / prefix) / 'share' / 'applications' / desktop

install:
    install -Dm0644 {{desktop-src}} {{desktop-dst}}

uninstall:
    rm -f {{desktop-dst}}
