appid := env_var('APPID')
install-dir := env_var('INSTALL_DIR')

desktop-src := appid + '.desktop'
desktop-dst := install-dir / 'applications' / desktop-src

icon-src := 'icons' / appid + '.svg'
icon-dst := install-dir / 'icons' / 'hicolor' / 'scalable' / 'apps' / appid + '.svg'

install:
    install -Dm0644 {{desktop-src}} {{desktop-dst}}
    install -Dm0644 {{icon-src}} {{icon-dst}}

uninstall:
    rm -f {{desktop-dst}}
    rm -f {{icon-dst}}
