rootdir := ''
prefix := '/usr'

base-dir := absolute_path(clean(rootdir / prefix))

desktop := APPID + '.desktop'
desktop-src := APPID + '.desktop'
desktop-dst := clean(rootdir / prefix) / 'share' / 'applications' / desktop

icon := APPID + '.svg'
icon-src := 'icons' / icon
icon-dst := clean(rootdir / prefix) / 'share' / 'icons' / 'hicolor' / 'scalable' / 'apps' / icon

install:
    install -Dm0644 {{desktop-src}} {{desktop-dst}}
    install -Dm0644 {{icon-src}} {{icon-dst}}

uninstall:
    rm -f {{desktop-dst}}
    rm -f {{icon-dst}}
